name: Publish package to npm
on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: NPM

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}